# -*- coding: utf-8 -*-
from __future__ import print_function


class CountrySubdomain:
    def __init__(self):
        self._subdomains = {
            'Romania':'.ro',
            'Kenya':'.ke',
            'Kyrgyzstan':'.kg',
            'Cambodia':'.kh',
            'Kiribati':'.ki',
            'Comoros':'.km',
            'Saint Kitts and Nevis':'.kn',
            'Democratic People\'s Republic of Korea':'.kp',
            'Republic of Korea':'.kr',
            'Kuwait':'.kw',
            'Serbia':'.rs',
            'Cayman Islands':'.ky',
            'Kazakhstan':'.kz',
            'Rwanda':'.rw',
            'Russia':'.ru',
            'Belize':'.bz',
            'Belarus':'.by',
            'Uzbekistan':'.uz',
            'Uruguay':'.uy',
            'Bahamas':'.bs',
            'Brazil':'.br',
            'Botswana':'.bw',
            'Bouvet Island':'.bv',
            'Bhutan':'.bt',
            'Benin':'.bj',
            'Burundi':'.bi',
            'Bahrain':'.bh',
            'Bolivia':'.bo',
            'Brunei':'.bn',
            'Bermuda':'.bm',
            'Barbados':'.bb',
            'Bosnia and Herzegovina':'.ba',
            'Bulgaria':'.bg',
            'Burkina Faso':'.bf',
            'Belgium':'.be',
            'Bangladesh':'.bd',
            'Western Sahara':'.eh',
            'Egypt':'.eg',
            'Estonia':'.ee',
            'Ecuador':'.ec',
            'Ethiopia':'.et',
            'European Union':'.eu',
            'Eritrea':'.er',
            'Spain':'.es',
            'Saint-Pierre and Miquelon':'.pm',
            'Poland':'.pl',
            'Pitcairn Islands':'.pn',
            'India':'.in',
            'British Indian Ocean Territory':'.io',
            'Israel':'.il',
            'Isle of Man':'.im',
            'Peru':'.pe',
            'Papua New Guinea':'.pg',
            'French Polynesia':'.pf',
            'Panama':'.pa',
            'Indonesia':'.id',
            'Ireland':'.ie',
            'Paraguay':'.py',
            'Uganda':'.ug',
            'Iran':'.ir',
            'Iceland':'.is',
            'Palau':'.pw',
            'Iraq':'.iq',
            'Italy':'.it',
            'Puerto Rico':'.pr',
            'Seychelles':'.sc',
            'Sint Maarten':'.sx',
            'Syria':'.sy',
            'Yemen':'.ye',
            'Oman':'.om',
            'Vanuatu':'.vu',
            'British Virgin Islands':'.vg',
            'Venezuela':'.ve',
            'Tanzania':'.tz',
            'Saint Vincent and the Grenadines':'.vc',
            'Vatican City':'.va',
            'Vietnam':'.vn',
            'United States Virgin Islands':'.vi',
            'Faroe Islands':'.fo',
            'Federated States of Micronesia':'.fm',
            'Falkland Islands':'.fk',
            'Fiji':'.fj',
            'Finland':'.fi',
            'France':'.fr',
            'Turkey':'.tr',
            'Réunion':'.re',
            'Taiwan':'.tw',
            'Tuvalu':'.tv',
            'Thailand':'.th',
            'Tokelau':'.tk',
            'Mayotte':'.yt',
            'SFR Yugoslavia FR Yugoslavia':'.yu',
            'Tajikistan':'.tj',
            'East Timor':'.tl',
            'Maldives':'.mv',
            'Malawi':'.mw',
            'Malta':'.mt',
            'Mauritius':'.mu',
            'Mauritania':'.mr',
            'Montserrat':'.ms',
            'Northern Mariana Islands':'.mp',
            'Martinique':'.mq',
            'East Timor':'.tp',
            'Tunisia':'.tn',
            'Mozambique':'.mz',
            'Trinidad and Tobago':'.tt',
            'Mexico':'.mx',
            'Malaysia':'.my',
            'Madagascar':'.mg',
            'Moldova':'.md',
            'Montenegro':'.me',
            'Turkmenistan':'.tm',
            'Monaco':'.mc',
            'Tonga':'.to',
            'Morocco':'.ma',
            'Mongolia':'.mn',
            'Macau':'.mo',
            'Mali':'.ml',
            'Myanmar':'.mm',
            'Macedonia':'.mk',
            'Marshall Islands':'.mh',
            'French Southern and Antarctic Lands':'.tf',
            'Denmark':'.dk',
            'Djibouti':'.dj',
            'Dominica':'.dm',
            'Dominican Republic':'.do',
            'Germany':'.de',
            'East Germany':'.dd',
            'Chad':'.td',
            'Algeria':'.dz',
            'Togo':'.tg',
            'United States of America':'.us',
            'Turks and Caicos Islands':'.tc',
            'United Kingdom':'.uk',
            'Christmas Island':'.cx',
            'Cyprus':'.cy',
            'Czech Republic':'.cz',
            'Costa Rica':'.cr',
            'Czechoslovakia':'.cs',
            'Cuba':'.cu',
            'Cape Verde':'.cv',
            'Curaçao':'.cw',
            'Switzerland':'.ch',
            'Côte d\'Ivoire':'.ci',
            'Cook Islands':'.ck',
            'Chile':'.cl',
            'Cameroon':'.cm',
            'People\'s Republic of China':'.cn',
            'Colombia':'.co',
            'Canada':'.ca',
            'Cocos (Keeling) Islands':'.cc',
            'Democratic Republic of the Congo':'.cd',
            'Central African Republic':'.cf',
            'Republic of the Congo':'.cg',
            'Zimbabwe':'.zw',
            'South Africa':'.za',
            'Ukraine':'.ua',
            'Zambia':'.zm',
            'Jersey':'.je',
            'Jordan':'.jo',
            'Jamaica':'.jm',
            'Japan':'.jp',
            'Samoa':'.ws',
            'Saint Helena':'.sh',
            'Slovenia':'.si',
            'Svalbard and Jan MayenIslands':'.sj',
            'Slovakia':'.sk',
            'Sierra Leone':'.sl',
            'San Marino':'.sm',
            'Senegal':'.sn',
            'Somalia':'.so',
            'Heard Island and McDonald Islands':'.hm',
            'Saudi Arabia':'.sa',
            'Solomon Islands':'.sb',
            'Honduras':'.hn',
            'Sudan':'.sd',
            'Sweden':'.se',
            'Hong Kong':'.hk',
            'Singapore':'.sg',
            'Hungary':'.hu',
            'Haiti':'.ht',
            'Swaziland':'.sz',
            'Croatia':'.hr',
            'Suriname':'.sr',
            'South Sudan':'.ss',
            'São Tomé and Príncipe':'.st',
            'Soviet Union':'.su',
            'El Salvador':'.sv',
            'Wallis and Futuna':'.wf',
            'Philippines':'.ph',
            'Pakistan':'.pk',
            'Norway':'.no',
            'Netherlands':'.nl',
            'Nicaragua':'.ni',
            'Nigeria':'.ng',
            'Norfolk Island':'.nf',
            'Niger':'.ne',
            'New Caledonia':'.nc',
            'Namibia':'.na',
            'Qatar':'.qa',
            'New Zealand':'.nz',
            'Niue':'.nu',
            'Nauru':'.nr',
            'Nepal':'.np',
            'Ascension Island':'.ac',
            'Afghanistan':'.af',
            'Antigua and Barbuda':'.ag',
            'Andorra':'.ad',
            'United Arab Emirates':'.ae',
            'Anguilla':'.ai',
            'Netherlands Antilles':'.an',
            'Angola':'.ao',
            'Albania':'.al',
            'Armenia':'.am',
            'Argentina':'.ar',
            'American Samoa':'.as',
            'Antarctica':'.aq',
            'Aruba':'.aw',
            'Austria':'.at',
            'Australia':'.au',
            'Azerbaijan':'.az',
            'Åland':'.ax',
            'Portugal':'.pt',
            'State of Palestine':'.ps',
            'Lesotho':'.ls',
            'Liberia':'.lr',
            'Luxembourg':'.lu',
            'Lithuania':'.lt',
            'Latvia':'.lv',
            'Libya':'.ly',
            'Laos':'.la',
            'Saint Lucia':'.lc',
            'Lebanon':'.lb',
            'Liechtenstein':'.li',
            'Sri Lanka':'.lk',
            'Grenada':'.gd',
            'Georgia':'.ge',
            'French Guiana':'.gf',
            'Guernsey':'.gg',
            'Gabon':'.ga',
            'United Kingdom':'.gb',
            'Greenland':'.gl',
            'The Gambia':'.gm',
            'Guinea':'.gn',
            'Ghana':'.gh',
            'Gibraltar':'.gi',
            'Guatemala':'.gt',
            'Guam':'.gu',
            'Guinea-Bissau':'.gw',
            'Guadeloupe':'.gp',
            'Equatorial Guinea':'.gq',
            'Greece':'.gr',
            'South Georgia and the South Sandwich Islands':'.gs',
            'Guyana':'.gy',
        }
    
    def get_subdomain(self, country, dot=False):
        '''
            Get the subdomain for country.
            country -> the name of the country, mandatory parameter.
            dot -> default False, if True the return subdomain 
            contain the initial dot.
        '''
        country = self._beatifullize(country)
        subdomain = self._subdomains.get(country, 'Not subdomain for country named "%s"' % (country,))
        
        if not dot:
            return subdomain
        else:
            return subdomain[1:]
        
    def _beatifullize(self, text):
        '''
            Beautify the country name to match the keys of the dictionary.
        '''
        words = text.split(' ')
        text = ''
        for word in words:
            print(word)
            text = text + ' ' + word.capitalize()
            
        return text[1:]
        
    def _convert(self):
        '''
            Utility to reverse the order of dictionary subdomains.
        '''
        f=open('./reverse.txt', 'w+')
        for k, v in self._subdomains.iteritems():
            line = "'%s':'%s'," % (v, k,)
            print(line, file=f)
        f.close()
            